# Generated by Django 3.2.13 on 2022-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_jobdata_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='pseudo_position',
            field=models.CharField(max_length=255),
        ),
    ]
